databases:
  - name: icecream_DB
    databaseName: icecream_db
    user: icecream
    region: singapore

services:
  - type: web
    name: icecream
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: icecream_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false